#!/usr/bin/env bash
# Undo node
npm uninstall -g yarn typescript-language-server typescript
sudo apt purge nodejs npm
rm /usr/local/lib/node_modules/n/bin/n
rm /usr/local/bin/n
rm /usr/local/bin/node

# Undo Core Install
sudo apt -y purge curl htop stow tmux build-essential golang fzf lsof ccache ninja-build yarn python3-pip xclip dconf-editor tldr
