- name: Workspace init
  hosts: localhost
  vars:
      source_key: './.ssh/id_ed25519'
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
      personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
      - name: Update Apt
        become: true
        ansible.builtin.apt:
            force_apt_get: true
            update_cache: true
            state: present
        tags:
            - install
            - core
  tasks:
      - ansible.builtin.import_tasks: tasks/core-setup.yml
      - ansible.builtin.import_tasks: tasks/stow-setup.yml
      - ansible.builtin.import_tasks: tasks/dotfiles.yml
      - ansible.builtin.import_tasks: tasks/gh-cli-setup.yml
      - ansible.builtin.import_tasks: tasks/git-setup.yml
      - ansible.builtin.import_tasks: tasks/golang-setup.yml
      - ansible.builtin.import_tasks: tasks/npm-packages.yml
      - ansible.builtin.import_tasks: tasks/nvm-setup.yml
      - ansible.builtin.import_tasks: tasks/personal-projects.yml
      - ansible.builtin.import_tasks: tasks/productivity-tools.yml
      - ansible.builtin.import_tasks: tasks/python-setup.yml
      - ansible.builtin.import_tasks: tasks/rust-setup.yml
      - ansible.builtin.import_tasks: tasks/ssh.yml
      - ansible.builtin.import_tasks: tasks/ts-setup.yml
