- name: 'Setup cht.sh'
  block:
      - name: 'Downloading cht.sh executable to .local/bin'
        ansible.builtin.get_url:
            url: https://cht.sh/:cht.sh
            dest: '{{ ansible_env.HOME }}/.local/bin'
            mode: '0755'
            force: true
