- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
      name: ['build-essential', 'cmake', 'pkg-config', 'libpthread-stubs0-dev']
  tags:
      - install
      - core

- name: Install System Packages 2 (unzip, libtool, libtool-bin)
  become: true
  apt:
      name: ['unzip', 'libtool', 'libtool-bin']
  tags:
      - install
      - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
      name:
          [
              'curl',
              'htop',
              'golang',
              'lsof',
              'ccache',
              'python3-pip',
              'dconf-editor',
              'moreutils',
          ]
  tags:
      - install
      - core
