- name: Installing stow
  apt: name=stow
  tags:
      - install
      - dotfiles
      - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
      repo: 'git@github.com:agSant01/.dotfiles.git'
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
  tags:
      - install
      - dotfiles
      - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  args:
      creates: '{{ ansible_env.HOME }}/.custom_dotfiles_env'
  register: out
  tags:
      - install
      - dotfiles
      - stow

- name: .dotfiles install stdout
  ansible.builtin.debug:
      msg: '{{ out.stdout_lines }}'
  tags:
      - install
      - dotfiles
      - stow
