- name: Cloning .dotfiles
  ansible.builtin.git:
      repo: 'git@github.com:agSant01/.dotfiles.git'
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: true
      update: true
      accept_hostkey: true
      version: main
  tags:
      - install
      - dotfiles
      - stow

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && ./install.sh
  args:
      creates: '{{ ansible_env.HOME }}/.custom_dotfiles_env'
  register: out
  tags:
      - install
      - dotfiles
      - stow

- name: .dotfiles install stdout
  ansible.builtin.debug:
      msg: '{{ out.stdout_lines }}'
  tags:
      - install
      - dotfiles
      - stow
