- name: Install Yarn
  community.general.npm:
      name: yarn
      global: true
  tags:
      - install
      - node

- name: Install eslint
  community.general.npm:
      name: eslint
      global: true
  tags:
      - install
      - node
