- name: Download and Install nvm
  ansible.builtin.shell: |
      set -o pipefail
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  args:
      executable: /bin/bash
      creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'
  tags:
      - install
      - node

- name: Install lts version of Node and NPM
  ansible.builtin.shell: 'source {{ ansible_env.HOME }}/.nvm/nvm.sh; nvm install --lts --latest-npm'
  become: true
  args:
      executable: /bin/bash
      creates: '{{ ansible_env.HOME }}/.nvm/versions/node'
  tags:
      - install
      - node
