- name: 'Peresonal Projects'
  tags: ['install', 'personal']
  become: false
  block:
      - name: 'Personal Project: Coding Problems Exists'
        register: codingprobs
        ansible.builtin.stat:
            path: '{{ personal }}/coding-problems'
      - name: 'Personal Project: Coding Problems' # noqa: latest[git]
        when: codingprobs.stat.exists
        ansible.builtin.git:
            repo: 'git@github.com:agSant01/coding-problems.git'
            dest: '{{ personal }}/coding-problems'
            version: HEAD

      - name: 'Personal Project: Random Meal Generator JS'
        register: randmgjs
        ansible.builtin.stat:
            path: '{{ personal }}/coding-problems'

      - name: 'Personal Project: Coding Problems' # noqa: latest[git]
        when: randmgjs.stat.exists
        ansible.builtin.git:
            repo: 'git@github.com:agSant01/random-meal-generator-js.git'
            dest: '{{ personal }}/random-meal-generator-js'

      - name: 'AOC Related'
        tags: 'aoc'
        block:
            - name: 'Personal Project: AdventOfCode Python Exists'
              register: aoc_py
              ansible.builtin.stat:
                  path: '{{ personal }}/advent-of-code-python'
            - name: 'Personal Project: AdventOfCode Python' # noqa: latest[git]
              when: aoc_py.stat.exists
              ansible.builtin.git:
                  repo: 'git@github.com:agSant01/advent-of-code-python.git'
                  dest: '{{ personal }}/advent-of-code-python'

            - name: 'Personal Project: AdventOfCode Rust Exists'
              ansible.builtin.stat:
                  path: '{{ personal }}/aoc-rust'
              register: aoc_rust
            - name: 'Personal Project: AdventOfCode Rust' # noqa: latest[git]
              when: aoc_rust.stat.exists
              ansible.builtin.git:
                  repo: 'git@github.com:agSant01/aoc-rust.git'
                  dest: '{{ personal }}/aoc-rust'
