- name: Productivity tools
  tags: ['install', 'productivity']
  become: false
  block:
      - name: 'Install developer productivity packages (tmux, tldr, fzf, etc.)'
        become: true
        ansible.builtin.apt:
            name:
                ['tmux', 'xclip', 'screenkey', 'tldr', 'ripgrep', 'tree', 'vim']
      - name: 'Fd-find setup'
        tags: fd
        ansible.builtin.import_tasks: productivity/fdfind.yml
      - name: 'Fzf setup'
        tags: fzf
        ansible.builtin.import_tasks: productivity/fzf.yml
      - name: 'Setup cht.sh'
        ansible.builtin.import_tasks: productivity/cheatsh.yml
      - name: 'Zoxide setup'
        ansible.builtin.import_tasks: productivity/zoxide.yml
      - name: 'jqlang/jq setup' # noqa:name[casing]
        ansible.builtin.import_tasks: productivity/jq-setup.yml
