- name: Productivity tools
  become: true
  tags: ['install', 'productivity']
  block:
    - name: 'Install developer productivity packages (tmux, tldr, fzf, etc.)'
      ansible.builtin.apt:
        name: ['tmux', 'xclip', 'screenkey', 'tldr', 'ripgrep']
    - name: 'Fd-find setup'
      ansible.builtin.import_tasks: productivity/fdfind.yml
    - name: 'Fzf setup'
      ansible.builtin.import_tasks: productivity/fzf.yml
    - name: 'Setup cht.sh'
      ansible.builtin.import_tasks: productivity/cheatsh.yml
