- name: Setup python
  tags: ['install', 'python']
  block:
    - name: Install Python3 and Virtualenv
      become: true
      ansible.builtin.apt:
        name: ['python3', 'python3-pip', 'virtualenv']

    - name: Install pip packages (ansible-lint, etc.)
      ansible.builtin.pip:
        break_system_packages: true
        name: ['ansible-lint']
