- name: Setup SSH
  tags:
      - dotfiles
      - install
      - ssh
  block:
      - name: Ensure .ssh directory exists.
        ansible.builtin.file:
            dest: '{{ dest_key | dirname }}'
            mode: '0700'
            state: directory

      - name: Install ssh key
        ansible.builtin.copy:
            src: '{{ source_key }}'
            dest: '{{ dest_key }}'
            mode: '0600'

      - name: Install ssh key public
        ansible.builtin.copy:
            src: '{{ source_key }}.pub'
            dest: '{{ dest_key }}.pub'
            mode: '0644'

      - name: Set authorized key took from file
        ansible.posix.authorized_key:
            key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
            path: "{{ lookup('env', 'HOME') }}/.ssh/authorized_keys"
            user: "{{ lookup('env', 'USER') }}"
            manage_dir: false
            state: present
